/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MinecraftRouteImport } from './routes/minecraft'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VpsRouteImport } from './routes/vps'
import { Route as AuthenticatedFreeRouteImport } from './routes/_authenticated/free'
import { Route as AuthenticatedFreeIndexRouteImport } from './routes/_authenticated/free.index'
import { Route as AuthenticatedFreeAfkRouteImport } from './routes/_authenticated/free.afk'
import { Route as AuthenticatedFreeCreateRouteImport } from './routes/_authenticated/free.create'
import { Route as AuthenticatedFreeJoinRouteImport } from './routes/_authenticated/free.join'
import { Route as AuthenticatedFreeRedeemRouteImport } from './routes/_authenticated/free.redeem'
import { Route as AuthenticatedFreeShopRouteImport } from './routes/_authenticated/free.shop'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MinecraftRoute = MinecraftRouteImport.update({
  id: '/minecraft',
  path: '/minecraft',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VpsRoute = VpsRouteImport.update({
  id: '/vps',
  path: '/vps',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFreeRoute = AuthenticatedFreeRouteImport.update({
  id: '/free',
  path: '/free',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFreeIndexRoute = AuthenticatedFreeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedFreeRoute,
} as any)
const AuthenticatedFreeAfkRoute = AuthenticatedFreeAfkRouteImport.update({
  id: '/afk',
  path: '/afk',
  getParentRoute: () => AuthenticatedFreeRoute,
} as any)
const AuthenticatedFreeCreateRoute = AuthenticatedFreeCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthenticatedFreeRoute,
} as any)
const AuthenticatedFreeJoinRoute = AuthenticatedFreeJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => AuthenticatedFreeRoute,
} as any)
const AuthenticatedFreeRedeemRoute = AuthenticatedFreeRedeemRouteImport.update({
  id: '/redeem',
  path: '/redeem',
  getParentRoute: () => AuthenticatedFreeRoute,
} as any)
const AuthenticatedFreeShopRoute = AuthenticatedFreeShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AuthenticatedFreeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/minecraft': typeof MinecraftRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/vps': typeof VpsRoute
  '/free': typeof AuthenticatedFreeRouteWithChildren
  '/free/afk': typeof AuthenticatedFreeAfkRoute
  '/free/create': typeof AuthenticatedFreeCreateRoute
  '/free/join': typeof AuthenticatedFreeJoinRoute
  '/free/redeem': typeof AuthenticatedFreeRedeemRoute
  '/free/shop': typeof AuthenticatedFreeShopRoute
  '/free/': typeof AuthenticatedFreeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/minecraft': typeof MinecraftRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/vps': typeof VpsRoute
  '/free/afk': typeof AuthenticatedFreeAfkRoute
  '/free/create': typeof AuthenticatedFreeCreateRoute
  '/free/join': typeof AuthenticatedFreeJoinRoute
  '/free/redeem': typeof AuthenticatedFreeRedeemRoute
  '/free/shop': typeof AuthenticatedFreeShopRoute
  '/free': typeof AuthenticatedFreeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/minecraft': typeof MinecraftRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/vps': typeof VpsRoute
  '/_authenticated/free': typeof AuthenticatedFreeRouteWithChildren
  '/_authenticated/free/afk': typeof AuthenticatedFreeAfkRoute
  '/_authenticated/free/create': typeof AuthenticatedFreeCreateRoute
  '/_authenticated/free/join': typeof AuthenticatedFreeJoinRoute
  '/_authenticated/free/redeem': typeof AuthenticatedFreeRedeemRoute
  '/_authenticated/free/shop': typeof AuthenticatedFreeShopRoute
  '/_authenticated/free/': typeof AuthenticatedFreeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/minecraft'
    | '/privacy'
    | '/terms'
    | '/vps'
    | '/free'
    | '/free/afk'
    | '/free/create'
    | '/free/join'
    | '/free/redeem'
    | '/free/shop'
    | '/free/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/minecraft'
    | '/privacy'
    | '/terms'
    | '/vps'
    | '/free/afk'
    | '/free/create'
    | '/free/join'
    | '/free/redeem'
    | '/free/shop'
    | '/free'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/minecraft'
    | '/privacy'
    | '/terms'
    | '/vps'
    | '/_authenticated/free'
    | '/_authenticated/free/afk'
    | '/_authenticated/free/create'
    | '/_authenticated/free/join'
    | '/_authenticated/free/redeem'
    | '/_authenticated/free/shop'
    | '/_authenticated/free/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  MinecraftRoute: typeof MinecraftRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  VpsRoute: typeof VpsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minecraft': {
      id: '/minecraft'
      path: '/minecraft'
      fullPath: '/minecraft'
      preLoaderRoute: typeof MinecraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vps': {
      id: '/vps'
      path: '/vps'
      fullPath: '/vps'
      preLoaderRoute: typeof VpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/free': {
      id: '/_authenticated/free'
      path: '/free'
      fullPath: '/free'
      preLoaderRoute: typeof AuthenticatedFreeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/free/': {
      id: '/_authenticated/free/'
      path: '/'
      fullPath: '/free/'
      preLoaderRoute: typeof AuthenticatedFreeIndexRouteImport
      parentRoute: typeof AuthenticatedFreeRoute
    }
    '/_authenticated/free/afk': {
      id: '/_authenticated/free/afk'
      path: '/afk'
      fullPath: '/free/afk'
      preLoaderRoute: typeof AuthenticatedFreeAfkRouteImport
      parentRoute: typeof AuthenticatedFreeRoute
    }
    '/_authenticated/free/create': {
      id: '/_authenticated/free/create'
      path: '/create'
      fullPath: '/free/create'
      preLoaderRoute: typeof AuthenticatedFreeCreateRouteImport
      parentRoute: typeof AuthenticatedFreeRoute
    }
    '/_authenticated/free/join': {
      id: '/_authenticated/free/join'
      path: '/join'
      fullPath: '/free/join'
      preLoaderRoute: typeof AuthenticatedFreeJoinRouteImport
      parentRoute: typeof AuthenticatedFreeRoute
    }
    '/_authenticated/free/redeem': {
      id: '/_authenticated/free/redeem'
      path: '/redeem'
      fullPath: '/free/redeem'
      preLoaderRoute: typeof AuthenticatedFreeRedeemRouteImport
      parentRoute: typeof AuthenticatedFreeRoute
    }
    '/_authenticated/free/shop': {
      id: '/_authenticated/free/shop'
      path: '/shop'
      fullPath: '/free/shop'
      preLoaderRoute: typeof AuthenticatedFreeShopRouteImport
      parentRoute: typeof AuthenticatedFreeRoute
    }
  }
}

interface AuthenticatedFreeRouteChildren {
  AuthenticatedFreeAfkRoute: typeof AuthenticatedFreeAfkRoute
  AuthenticatedFreeCreateRoute: typeof AuthenticatedFreeCreateRoute
  AuthenticatedFreeJoinRoute: typeof AuthenticatedFreeJoinRoute
  AuthenticatedFreeRedeemRoute: typeof AuthenticatedFreeRedeemRoute
  AuthenticatedFreeShopRoute: typeof AuthenticatedFreeShopRoute
  AuthenticatedFreeIndexRoute: typeof AuthenticatedFreeIndexRoute
}

const AuthenticatedFreeRouteChildren: AuthenticatedFreeRouteChildren = {
  AuthenticatedFreeAfkRoute: AuthenticatedFreeAfkRoute,
  AuthenticatedFreeCreateRoute: AuthenticatedFreeCreateRoute,
  AuthenticatedFreeJoinRoute: AuthenticatedFreeJoinRoute,
  AuthenticatedFreeRedeemRoute: AuthenticatedFreeRedeemRoute,
  AuthenticatedFreeShopRoute: AuthenticatedFreeShopRoute,
  AuthenticatedFreeIndexRoute: AuthenticatedFreeIndexRoute,
}

const AuthenticatedFreeRouteWithChildren =
  AuthenticatedFreeRoute._addFileChildren(AuthenticatedFreeRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedFreeRoute: typeof AuthenticatedFreeRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedFreeRoute: AuthenticatedFreeRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  MinecraftRoute: MinecraftRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  VpsRoute: VpsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
